spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  jpa:
    hibernate:
      ddl-auto: update
      hbm2ddl:
        auto: update
    show-sql: true
    generate-ddl: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

org:
   jobrunr:
     job-scheduler:
       enabled: true
     background-job-server:
            enabled: true
     dashboard:
       enabled: true
       port: 8000
