spring:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_db
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

