spring:
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: jdbc:h2:file:C:/data/spring-batch-db
#    username: sa
#    password: sa
#    driverClassName: org.h2.Driver

